# Generated by Codex on 2026-06-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='启用视觉辅助')),
                (
                    'provider',
                    models.CharField(
                        choices=[
                            ('openai', 'OpenAI'),
                            ('anthropic', 'Anthropic（A社 / Claude）'),
                            ('openai_compatible', '第三方 OpenAI-compatible'),
                        ],
                        default='openai',
                        max_length=32,
                        verbose_name='服务商',
                    ),
                ),
                ('provider_name', models.CharField(blank=True, default='', max_length=80, verbose_name='第三方名称')),
                ('api_key', models.CharField(blank=True, default='', max_length=512, verbose_name='API Key')),
                ('base_url', models.URLField(blank=True, default='', max_length=300, verbose_name='Base URL')),
                ('model', models.CharField(blank=True, default='gpt-4o-mini', max_length=120, verbose_name='模型')),
                (
                    'prompt',
                    models.TextField(
                        blank=True,
                        default=(
                            '你是订单截图结构化助手。请从图片中提取真实商品/食材行，忽略订单号、地址、配送费、优惠、'
                            '合计、支付方式、按钮文案和售后文案。只返回 JSON，不要输出解释。格式：'
                            '{"items":[{"dish_name":"食材名称","quantity":1,"unit_price":12.3,"subtotal":12.3}],'
                            '"raw_text":"可选，概括识别到的关键文本"}。数量无法判断时填 1，价格无法判断时填 null。'
                        ),
                        verbose_name='识别提示词',
                    ),
                ),
                ('timeout_seconds', models.PositiveIntegerField(default=60, verbose_name='请求超时(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_vision_configs',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='创建者',
                    ),
                ),
                (
                    'updated_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='updated_vision_configs',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='更新者',
                    ),
                ),
            ],
            options={
                'verbose_name': '视觉辅助配置',
                'verbose_name_plural': '视觉辅助配置',
            },
        ),
    ]
