# Generated by Django 5.2.11 on 2026-02-19 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(db_index=True, verbose_name='订单日期')),
                ('source', models.CharField(choices=[('ocr', 'OCR识别'), ('manual', '手动录入')], default='ocr', max_length=20, verbose_name='数据来源')),
                ('ocr_image', models.ImageField(blank=True, upload_to='ocr_uploads/', verbose_name='OCR截图')),
                ('ocr_raw_text', models.TextField(blank=True, default='', verbose_name='OCR原始文本')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('total_items', models.IntegerField(default=0, verbose_name='总菜品数')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=100, verbose_name='菜品名称(原始)')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='数量')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='单价')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='小计')),
                ('is_matched', models.BooleanField(default=False, verbose_name='已匹配')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='dishes.dish', verbose_name='关联菜品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='订单')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
            },
        ),
        migrations.CreateModel(
            name='DailyDishStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_date', models.DateField(db_index=True, verbose_name='统计日期')),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总量')),
                ('order_count', models.IntegerField(default=0, verbose_name='订单数')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总金额')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='dishes.dish', verbose_name='菜品')),
            ],
            options={
                'verbose_name': '每日菜品统计',
                'verbose_name_plural': '每日菜品统计',
                'ordering': ['-stat_date'],
                'unique_together': {('dish', 'stat_date')},
            },
        ),
    ]
