# Generated by Django 4.2.9 on 2026-02-19 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_alter_dish_options_alter_dishcategory_options_and_more'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailydishstatistic',
            options={'ordering': ['-stat_date'], 'verbose_name': '每日食材统计', 'verbose_name_plural': '每日食材统计'},
        ),
        migrations.AlterField(
            model_name='dailydishstatistic',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='dishes.dish', verbose_name='食材'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_items',
            field=models.IntegerField(default=0, verbose_name='总食材数'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='dishes.dish', verbose_name='关联食材'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='dish_name',
            field=models.CharField(max_length=100, verbose_name='食材名称(原始)'),
        ),
    ]
