# Generated by Django 5.2.11 on 2026-02-19 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('icon', models.CharField(blank=True, default='', max_length=10, verbose_name='图标')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '菜品分类',
                'verbose_name_plural': '菜品分类',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='菜品名称')),
                ('unit', models.CharField(default='份', max_length=20, verbose_name='计量单位')),
                ('default_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='默认单价')),
                ('image', models.ImageField(blank=True, upload_to='dish_images/', verbose_name='菜品图片')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='启用')),
                ('total_ordered', models.IntegerField(default=0, verbose_name='累计订购量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='dishes.dishcategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '菜品',
                'verbose_name_plural': '菜品',
                'ordering': ['-updated_at'],
            },
        ),
    ]
