# Generated by Django 4.2.9 on 2026-02-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['-updated_at'], 'verbose_name': '食材', 'verbose_name_plural': '食材'},
        ),
        migrations.AlterModelOptions(
            name='dishcategory',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '食材分类', 'verbose_name_plural': '食材分类'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, upload_to='dish_images/', verbose_name='食材图片'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='食材名称'),
        ),
    ]
