# Generated by Django 4.2.9 on 2026-02-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_alter_dish_options_alter_dishcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='specification',
            field=models.CharField(blank=True, default='', help_text='如: 500g/袋、1kg/盒', max_length=100, verbose_name='规格'),
        ),
        migrations.AddField(
            model_name='dish',
            name='storage',
            field=models.CharField(choices=[('常温', '常温'), ('冷藏', '冷藏'), ('冷冻', '冷冻')], default='常温', max_length=10, verbose_name='储存方式'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='default_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='参考单价'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='total_ordered',
            field=models.IntegerField(default=0, verbose_name='累计用量'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='unit',
            field=models.CharField(default='斤', max_length=20, verbose_name='计量单位'),
        ),
    ]
