# Generated by Django 4.2.9 on 2026-02-19 13:32

from django.db import migrations

CATEGORIES = [
    {'name': '肉禽蛋类', 'icon': '🥩', 'sort_order': 1},
    {'name': '蔬菜类', 'icon': '🥬', 'sort_order': 2},
    {'name': '水果类', 'icon': '🍎', 'sort_order': 3},
    {'name': '水产海鲜', 'icon': '🐟', 'sort_order': 4},
    {'name': '豆制品', 'icon': '🫘', 'sort_order': 5},
    {'name': '菌菇类', 'icon': '🍄', 'sort_order': 6},
    {'name': '粮油干货', 'icon': '🍚', 'sort_order': 7},
    {'name': '调味品', 'icon': '🧂', 'sort_order': 8},
    {'name': '乳品饮料', 'icon': '🥛', 'sort_order': 9},
    {'name': '冷冻食品', 'icon': '🧊', 'sort_order': 10},
    {'name': '其他', 'icon': '📦', 'sort_order': 99},
]


def populate_categories(apps, schema_editor):
    DishCategory = apps.get_model('dishes', 'DishCategory')
    for cat in CATEGORIES:
        DishCategory.objects.get_or_create(
            name=cat['name'],
            defaults={'icon': cat['icon'], 'sort_order': cat['sort_order']},
        )


def reverse_populate(apps, schema_editor):
    DishCategory = apps.get_model('dishes', 'DishCategory')
    names = [c['name'] for c in CATEGORIES]
    DishCategory.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_dish_specification_dish_storage_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_categories, reverse_populate),
    ]
