# Generated by Codex on 2026-02-20

from django.db import migrations

SIMPLIFIED_CATEGORIES = [
    {'name': '肉禽蛋类', 'icon': '🥩', 'sort_order': 1},
    {'name': '蔬果类', 'icon': '🥬', 'sort_order': 2},
    {'name': '水产豆菌类', 'icon': '🐟', 'sort_order': 3},
    {'name': '粮油调味', 'icon': '🍚', 'sort_order': 4},
    {'name': '乳品饮料', 'icon': '🥛', 'sort_order': 5},
    {'name': '其他', 'icon': '📦', 'sort_order': 99},
]


OLD_TO_NEW = {
    '肉禽蛋类': '肉禽蛋类',
    '蔬菜类': '蔬果类',
    '水果类': '蔬果类',
    '水产海鲜': '水产豆菌类',
    '豆制品': '水产豆菌类',
    '菌菇类': '水产豆菌类',
    '粮油干货': '粮油调味',
    '调味品': '粮油调味',
    '乳品饮料': '乳品饮料',
    '冷冻食品': '其他',
    '其他': '其他',
}


def simplify_categories(apps, schema_editor):
    Dish = apps.get_model('dishes', 'Dish')
    DishCategory = apps.get_model('dishes', 'DishCategory')

    new_categories = {}
    for cat in SIMPLIFIED_CATEGORIES:
        obj, _ = DishCategory.objects.get_or_create(
            name=cat['name'],
            defaults={'icon': cat['icon'], 'sort_order': cat['sort_order']},
        )
        updated = False
        if obj.icon != cat['icon']:
            obj.icon = cat['icon']
            updated = True
        if obj.sort_order != cat['sort_order']:
            obj.sort_order = cat['sort_order']
            updated = True
        if updated:
            obj.save(update_fields=['icon', 'sort_order'])
        new_categories[obj.name] = obj

    for old_name, new_name in OLD_TO_NEW.items():
        try:
            old_category = DishCategory.objects.get(name=old_name)
        except DishCategory.DoesNotExist:
            continue

        target = new_categories.get(new_name)
        if not target or old_category.id == target.id:
            continue

        Dish.objects.filter(category_id=old_category.id).update(category_id=target.id)

    keep_names = {c['name'] for c in SIMPLIFIED_CATEGORIES}
    obsolete_default_names = [name for name in OLD_TO_NEW.keys() if name not in keep_names]
    DishCategory.objects.filter(name__in=obsolete_default_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0004_populate_categories'),
    ]

    operations = [
        migrations.RunPython(simplify_categories, migrations.RunPython.noop),
    ]
