# Generated by Codex on 2026-02-20

from django.db import migrations

LEGACY_TO_SIMPLIFIED = {
    '荤菜': '肉禽蛋类',
    '素菜': '蔬果类',
    '主食': '粮油调味',
    '饮品': '乳品饮料',
    '小吃': '粮油调味',
    '汤类': '其他',
}


def merge_legacy_categories(apps, schema_editor):
    Dish = apps.get_model('dishes', 'Dish')
    DishCategory = apps.get_model('dishes', 'DishCategory')

    target_categories = {}
    for name in set(LEGACY_TO_SIMPLIFIED.values()):
        cat, _ = DishCategory.objects.get_or_create(name=name)
        target_categories[name] = cat

    for legacy_name, target_name in LEGACY_TO_SIMPLIFIED.items():
        try:
            legacy = DishCategory.objects.get(name=legacy_name)
        except DishCategory.DoesNotExist:
            continue

        target = target_categories.get(target_name)
        if target and legacy.id != target.id:
            Dish.objects.filter(category_id=legacy.id).update(category_id=target.id)
            legacy.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0005_simplify_dish_categories'),
    ]

    operations = [
        migrations.RunPython(merge_legacy_categories, migrations.RunPython.noop),
    ]
