# Generated by Django 5.2.11 on 2026-02-20 06:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_merge_legacy_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='stock_in_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='入库日期'),
        ),
    ]
