# Generated by Codex on 2026-02-20

import re

from django.db import migrations

CATEGORY_DEFINITIONS = [
    {'name': '肉禽蛋类', 'icon': '🥩', 'sort_order': 1},
    {'name': '蔬果类', 'icon': '🥬', 'sort_order': 2},
    {'name': '水产海鲜', 'icon': '🐟', 'sort_order': 3},
    {'name': '豆菌类', 'icon': '🍄', 'sort_order': 4},
    {'name': '粮油调味', 'icon': '🍚', 'sort_order': 5},
    {'name': '乳品饮料', 'icon': '🥛', 'sort_order': 6},
    {'name': '其他', 'icon': '📦', 'sort_order': 99},
]

AQUATIC_KEYWORDS = [
    '三文鱼', '金枪鱼', '鱿鱼', '章鱼', '扇贝', '生蚝', '蛤蜊', '带鱼', '虾仁', '海带',
    '紫菜', '海参', '鲍鱼', '龙虾', '螃蟹', '大虾', '鱼', '虾', '蟹', '贝', '海鲜',
]


def _normalize_name(name: str) -> str:
    return re.sub(r'[\s·\-—_*#•,，/（）()【】\[\]]+', '', (name or '').lower())


def split_aquatic_category(apps, schema_editor):
    Dish = apps.get_model('dishes', 'Dish')
    DishCategory = apps.get_model('dishes', 'DishCategory')

    category_map = {}
    for cat in CATEGORY_DEFINITIONS:
        obj, _ = DishCategory.objects.get_or_create(
            name=cat['name'],
            defaults={'icon': cat['icon'], 'sort_order': cat['sort_order']},
        )
        updated = False
        if obj.icon != cat['icon']:
            obj.icon = cat['icon']
            updated = True
        if obj.sort_order != cat['sort_order']:
            obj.sort_order = cat['sort_order']
            updated = True
        if updated:
            obj.save(update_fields=['icon', 'sort_order'])
        category_map[obj.name] = obj

    aquatic = category_map['水产海鲜']
    bean_mushroom = category_map['豆菌类']

    normalized_aquatic = []
    for keyword in AQUATIC_KEYWORDS:
        key = _normalize_name(keyword)
        if key:
            normalized_aquatic.append(key)

    # 历史合并分类：按关键字拆分到“水产海鲜”或“豆菌类”
    try:
        combined = DishCategory.objects.get(name='水产豆菌类')
    except DishCategory.DoesNotExist:
        combined = None

    if combined:
        dishes = Dish.objects.filter(category_id=combined.id).only('id', 'name')
        for dish in dishes:
            normalized_name = _normalize_name(dish.name)
            target = bean_mushroom
            if normalized_name and any(key in normalized_name for key in normalized_aquatic):
                target = aquatic
            Dish.objects.filter(id=dish.id).update(category_id=target.id)

        if combined.id not in (aquatic.id, bean_mushroom.id):
            combined.delete()

    # 若仍残留老分类，统一归并
    for legacy_name in ['豆制品', '菌菇类']:
        try:
            legacy = DishCategory.objects.get(name=legacy_name)
        except DishCategory.DoesNotExist:
            continue
        if legacy.id != bean_mushroom.id:
            Dish.objects.filter(category_id=legacy.id).update(category_id=bean_mushroom.id)
            legacy.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_dish_stock_in_date'),
    ]

    operations = [
        migrations.RunPython(split_aquatic_category, migrations.RunPython.noop),
    ]
