# Generated by Codex on 2026-02-20

from django.db import migrations, models
from django.utils import timezone


def backfill_deactivation_reason(apps, schema_editor):
    Dish = apps.get_model('dishes', 'Dish')
    today = timezone.localdate()
    Dish.objects.filter(is_active=False, deactivation_reason='').update(
        deactivation_reason='eaten',
        deactivated_at=today,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0008_split_aquatic_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='deactivated_at',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='停用日期'),
        ),
        migrations.AddField(
            model_name='dish',
            name='deactivation_reason',
            field=models.CharField(
                blank=True,
                choices=[('eaten', '吃完了'), ('discarded', '丢掉了')],
                db_index=True,
                default='',
                max_length=20,
                verbose_name='停用原因',
            ),
        ),
        migrations.RunPython(backfill_deactivation_reason, migrations.RunPython.noop),
    ]
