# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0009_dish_deactivation_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='total_ordered',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='累计用量'),
        ),
    ]
