# Generated by Codex on 2026-06-03

from django.db import migrations


def update_bean_mushroom_icon(apps, schema_editor):
    DishCategory = apps.get_model('dishes', 'DishCategory')
    DishCategory.objects.filter(name='豆菌类').update(icon='🍄')


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0010_alter_dish_total_ordered'),
    ]

    operations = [
        migrations.RunPython(update_bean_mushroom_icon, migrations.RunPython.noop),
    ]
