# Generated by Codex on 2026-06-07

import re

from django.db import migrations

SEASONING_KEYWORDS = [
    '葱', '小葱', '姜', '蒜', '香菜', '香葱', '生抽', '老抽', '蚝油', '料酒', '米醋',
    '陈醋', '白醋', '盐', '食盐', '白糖', '冰糖', '胡椒', '黑胡椒', '花椒', '八角',
    '桂皮', '香叶', '辣椒粉', '孜然', '香油', '芝麻', '鸡精', '味精', '调料', '佐料',
]


def _normalize_name(name: str) -> str:
    return re.sub(r'[\s·\-—_*#•,，/（）()【】\[\]]+', '', (name or '').lower())


def add_free_seasoning_category(apps, schema_editor):
    Dish = apps.get_model('dishes', 'Dish')
    DishCategory = apps.get_model('dishes', 'DishCategory')
    category, _ = DishCategory.objects.get_or_create(
        name='调料免费',
        defaults={'icon': '🧂', 'sort_order': 7},
    )
    updated = False
    if category.icon != '🧂':
        category.icon = '🧂'
        updated = True
    if category.sort_order != 7:
        category.sort_order = 7
        updated = True
    if updated:
        category.save(update_fields=['icon', 'sort_order'])

    normalized_keywords = [_normalize_name(keyword) for keyword in SEASONING_KEYWORDS]
    for dish in Dish.objects.all().only('id', 'name', 'category_id'):
        normalized = _normalize_name(dish.name)
        if normalized and any(keyword in normalized for keyword in normalized_keywords):
            Dish.objects.filter(id=dish.id).update(category_id=category.id)


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0011_update_bean_mushroom_icon'),
    ]

    operations = [
        migrations.RunPython(add_free_seasoning_category, migrations.RunPython.noop),
    ]
