# Generated by Django 5.2.11 on 2026-02-19 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分类名称')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('icon', models.CharField(blank=True, default='', max_length=10, verbose_name='图标')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '菜谱分类',
                'verbose_name_plural': '菜谱分类',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='菜谱名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='简介')),
                ('servings', models.IntegerField(default=1, verbose_name='份数')),
                ('prep_time_minutes', models.IntegerField(blank=True, null=True, verbose_name='准备时间(分钟)')),
                ('cook_time_minutes', models.IntegerField(blank=True, null=True, verbose_name='烹饪时间(分钟)')),
                ('difficulty', models.CharField(choices=[('简单', '简单'), ('中等', '中等'), ('困难', '困难')], default='中等', max_length=10, verbose_name='难度')),
                ('image', models.ImageField(blank=True, upload_to='recipe_images/', verbose_name='成品图片')),
                ('tips', models.TextField(blank=True, default='', verbose_name='小贴士')),
                ('is_published', models.BooleanField(default=True, verbose_name='已发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='dishes.dish', verbose_name='关联菜品')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='recipes.recipecategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '菜谱',
                'verbose_name_plural': '菜谱',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='食材名称')),
                ('amount', models.CharField(blank=True, default='', max_length=50, verbose_name='用量')),
                ('is_main', models.BooleanField(default=True, verbose_name='主料')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe', verbose_name='菜谱')),
            ],
            options={
                'verbose_name': '菜谱用料',
                'verbose_name_plural': '菜谱用料',
                'ordering': ['-is_main', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(verbose_name='步骤序号')),
                ('description', models.TextField(verbose_name='步骤描述')),
                ('image', models.ImageField(blank=True, upload_to='recipe_images/steps/', verbose_name='步骤图片')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe', verbose_name='菜谱')),
            ],
            options={
                'verbose_name': '菜谱步骤',
                'verbose_name_plural': '菜谱步骤',
                'ordering': ['step_number'],
            },
        ),
    ]
