# Generated by Django 5.2.11 on 2026-02-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.CharField(
                choices=[('local', '本地'), ('cooklikehoc', 'CookLikeHOC')],
                db_index=True,
                default='local',
                max_length=30,
                verbose_name='数据来源',
            ),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='来源ID'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_url',
            field=models.URLField(blank=True, default='', verbose_name='来源链接'),
        ),
    ]
