# Generated by Codex on 2026-02-20

from django.db import migrations

SIMPLIFIED_CATEGORIES = [
    {'name': '家常热菜', 'icon': '🍳', 'sort_order': 1},
    {'name': '主食早餐', 'icon': '🍚', 'sort_order': 2},
    {'name': '汤粥锅煲', 'icon': '🍲', 'sort_order': 3},
    {'name': '凉菜卤味', 'icon': '🥗', 'sort_order': 4},
    {'name': '炸烤小吃', 'icon': '🍤', 'sort_order': 5},
    {'name': '饮品配料', 'icon': '🥤', 'sort_order': 6},
    {'name': '其他', 'icon': '📦', 'sort_order': 99},
]

OLD_TO_NEW = {
    '炒菜': '家常热菜',
    '炖菜': '家常热菜',
    '蒸菜': '家常热菜',
    '烫菜': '家常热菜',
    '家常菜': '家常热菜',
    '川菜': '家常热菜',
    '粤菜': '家常热菜',
    '西餐': '家常热菜',
    '主食': '主食早餐',
    '早餐': '主食早餐',
    '汤': '汤粥锅煲',
    '煮锅': '汤粥锅煲',
    '砂锅菜': '汤粥锅煲',
    '凉拌': '凉菜卤味',
    '凉菜': '凉菜卤味',
    '卤菜': '凉菜卤味',
    '炸品': '炸烤小吃',
    '烤类': '炸烤小吃',
    '烘焙': '炸烤小吃',
    '饮品': '饮品配料',
    '配料': '饮品配料',
    '其他': '其他',
}


def simplify_recipe_categories(apps, schema_editor):
    Recipe = apps.get_model('recipes', 'Recipe')
    RecipeCategory = apps.get_model('recipes', 'RecipeCategory')

    new_categories = {}
    for cat in SIMPLIFIED_CATEGORIES:
        obj, _ = RecipeCategory.objects.get_or_create(
            name=cat['name'],
            defaults={'icon': cat['icon'], 'sort_order': cat['sort_order']},
        )
        updated = False
        if obj.icon != cat['icon']:
            obj.icon = cat['icon']
            updated = True
        if obj.sort_order != cat['sort_order']:
            obj.sort_order = cat['sort_order']
            updated = True
        if updated:
            obj.save(update_fields=['icon', 'sort_order'])
        new_categories[obj.name] = obj

    keep_names = {c['name'] for c in SIMPLIFIED_CATEGORIES}
    for old_category in RecipeCategory.objects.all():
        target_name = OLD_TO_NEW.get(old_category.name)
        if not target_name:
            if old_category.name in keep_names:
                target_name = old_category.name
            else:
                target_name = '其他'

        target = new_categories.get(target_name)
        if target and old_category.id != target.id:
            Recipe.objects.filter(category_id=old_category.id).update(category_id=target.id)

    RecipeCategory.objects.exclude(name__in=keep_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_source_fields'),
    ]

    operations = [
        migrations.RunPython(simplify_recipe_categories, migrations.RunPython.noop),
    ]
