# Generated by Django 5.2.11 on 2026-02-20 17:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_simplify_recipe_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeRecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='推荐日期')),
                ('score', models.FloatField(default=0, verbose_name='推荐分')),
                ('matched_ingredient_count', models.IntegerField(default=0, verbose_name='命中食材数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_histories', to='recipes.recipe', verbose_name='菜谱')),
            ],
            options={
                'verbose_name': '菜谱推荐历史',
                'verbose_name_plural': '菜谱推荐历史',
                'ordering': ['-recommended_date', '-created_at'],
                'unique_together': {('recipe', 'recommended_date')},
            },
        ),
    ]
