# Generated by Codex on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_reciperecommendationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='media_type',
            field=models.CharField(
                choices=[('none', '无'), ('image', '外部图片'), ('video', '外部视频')],
                default='none',
                max_length=20,
                verbose_name='媒体类型',
            ),
        ),
        migrations.AddField(
            model_name='recipe',
            name='media_title',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='媒体标题'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='media_url',
            field=models.URLField(blank=True, default='', verbose_name='媒体链接'),
        ),
    ]
