# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_media_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='external_links',
            field=models.JSONField(blank=True, default=list, verbose_name='外部菜谱链接'),
        ),
    ]
